import type { BusinessType, ShopSizeType, CarType } from "../types/business";
import type { CarOption } from "../types/business";
export const SHOP_SIZES: ShopSizeType[] = [
  { id: 1, name: "Невеликий магазин", multiplier: 1 },
  { id: 2, name: "Середня мережа", multiplier: 1.5 },
  { id: 3, name: "Крупна мережа", multiplier: 2 },
];

export const AVAILABLE_BUSINESSES: BusinessType[] = [
  {
    id: 1,
    name: "Продажа",
    type: "shop",
    incomePerHour: 50,
    price: 4899,
    icon: "cart-outline",
    color: "#2ecc71",
    isChain: true,
  },
  {
    id: 2,
    name: "Таксопарк",
    type: "taxi",
    incomePerHour: 0,
    price: 9999,
    icon: "car-outline",
    color: "#f1c40f",
    dependent: true,
  },
  {
    id: 3,
    name: "Перевозки",
    type: "transportation",
    incomePerHour: 200,
    price: 19899,
    icon: "cube-outline",
    color: "#e67e22",
  },
  {
    id: 4,
    name: "Производство",
    type: "production",
    incomePerHour: 400,
    price: 24999,
    icon: "business-outline",
    color: "#2980b9",
  },
  {
    id: 5,
    name: "Строительство",
    type: "construction",
    incomePerHour: 700,
    price: 35400,
    icon: "construct-outline",
    color: "#e74c3c",
  },
  {
    id: 6,
    name: "Автодилер",
    type: "cardealer",
    incomePerHour: 1000,
    price: 40000,
    icon: "car-sport-outline",
    color: "#2c3e50",
    dependent: true,
  },
  {
    id: 7,
    name: "Ресторан",
    type: "restaurant",
    incomePerHour: 1500,
    price: 55000,
    icon: "restaurant-outline",
    color: "#d35400",
  },
  {
    id: 8,
    name: "IT-компания",
    type: "itcompany",
    incomePerHour: 2500,
    price: 80000,
    icon: "laptop-outline",
    color: "#8e44ad",
  },
  {
    id: 9,
    name: "Отель",
    type: "hotel",
    incomePerHour: 4000,
    price: 120000,
    icon: "bed-outline",
    color: "#16a085",
  },
  {
    id: 10,
    name: "Авиакомпания",
    type: "airline",
    incomePerHour: 7000,
    price: 200000,
    icon: "airplane-outline",
    color: "#3498db",
    dependent: true,
  },
];

export const CAR_OPTIONS: CarOption[] = [
  {
    name: "Vada Grand",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "300 000 км",
    income: 560,
    price: 7853,
    type: "economy",
    mileage: 0,
    broken: false,
  },
  {
    name: "Renolt Logon",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "520 000 км",
    income: 560,
    price: 10800,
    type: "economy",
    mileage: 0,
    broken: false,
  },
  {
    name: "Hendaji Solaer",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "480 000 км",
    income: 560,
    price: 12262,
    type: "economy",
    mileage: 0,
    broken: false,
  },

  {
    name: "Luma Cruiser",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "380 000 км",
    income: 920,
    price: 21000,
    type: "comfort",
    mileage: 0,
    broken: false,
  },
  {
    name: "Skotta Octavian",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "420 000 км",
    income: 920,
    price: 22246,
    type: "comfort",
    mileage: 0,
    broken: false,
  },
  {
    name: "Tovari Comfort",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "400 000 км",
    income: 920,
    price: 23000,
    type: "comfort",
    mileage: 0,
    broken: false,
  },

  {
    name: "Grand Comfort Plus",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "350 000 км",
    income: 1500,
    price: 35000,
    type: "comfort_plus",
    mileage: 0,
    broken: false,
  },
  {
    name: "Vesta Lux",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "340 000 км",
    income: 1500,
    price: 36000,
    type: "comfort_plus",
    mileage: 0,
    broken: false,
  },

  {
    name: "Biz Elite",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "300 000 км",
    income: 2500,
    price: 50000,
    type: "business",
    mileage: 0,
    broken: false,
  },
  {
    name: "Executive Car",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "280 000 км",
    income: 2600,
    price: 52000,
    type: "business",
    mileage: 0,
    broken: false,
  },

  {
    name: "Premier Lux",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "250 000 км",
    income: 4000,
    price: 80000,
    type: "premier",
    mileage: 0,
    broken: false,
  },
  {
    name: "Royal Premier",
    image: require("../../../../../assets/images/mastercard.png"),
    resource: "240 000 км",
    income: 4200,
    price: 85000,
    type: "premier",
    mileage: 0,
    broken: false,
  },
];
export const CAR_TYPE_COLORS: Record<CarType, string> = {
  economy: "#f39c12",
  comfort: "#2ecc71",
  comfort_plus: "#9b59b6",
  business: "#3498db",
  premier: "#e74c3c",
};
export const AIRLINE_OPTIONS: CarOption[] = [
  {
    name: "Cessna 172",
    type: "economy",
    image: require("../../../../../assets/images/react-logo.png"),
    income: 12000,
    price: 150000,
    resource: "500 000 км",
    mileage: 0,
    broken: false,
  },
  {
    name: "Boeing 737",
    type: "business",
    image: require("../../../../../assets/images/react-logo.png"),
    income: 85000,
    price: 900000,
    resource: "2 000 000 км",
    mileage: 0,
    broken: false,
  },
];
