import type { BusinessType, ShopSizeType } from "@/screens/Business";

export const SHOP_SIZES: ShopSizeType[] = [
  { id: 1, name: "Невеликий магазин", multiplier: 1 },
  { id: 2, name: "Середня мережа", multiplier: 1.5 },
  { id: 3, name: "Крупна мережа", multiplier: 2 },
];

export const AVAILABLE_BUSINESSES: BusinessType[] = [
  {
    id: 1,
    name: "Продажа",
    type: "shop",
    incomePerHour: 50,
    price: 4899,
    icon: "cart-outline",
    color: "#2ecc71",
    isChain: true,
  },
  {
    id: 2,
    name: "Таксопарк",
    type: "taxi",
    incomePerHour: 100,
    price: 9999,
    icon: "car-outline",
    color: "#f1c40f",
    dependent: true,
  },
  {
    id: 3,
    name: "Перевозки",
    type: "transportation",
    incomePerHour: 200,
    price: 19899,
    icon: "cube-outline",
    color: "#e67e22",
  },
  {
    id: 4,
    name: "Производство",
    type: "production",
    incomePerHour: 400,
    price: 24999,
    icon: "business-outline",
    color: "#2980b9",
  },
  {
    id: 5,
    name: "Строительство",
    type: "construction",
    incomePerHour: 700,
    price: 35400,
    icon: "construct-outline",
    color: "#e74c3c",
  },
  {
    id: 6,
    name: "Автодилер",
    type: "cardealer",
    incomePerHour: 1000,
    price: 40000,
    icon: "car-sport-outline",
    color: "#2c3e50",
    dependent: true,
  },
  {
    id: 7,
    name: "Ресторан",
    type: "restaurant",
    incomePerHour: 1500,
    price: 55000,
    icon: "restaurant-outline",
    color: "#d35400",
  },
  {
    id: 8,
    name: "IT-компания",
    type: "itcompany",
    incomePerHour: 2500,
    price: 80000,
    icon: "laptop-outline",
    color: "#8e44ad",
  },
  {
    id: 9,
    name: "Отель",
    type: "hotel",
    incomePerHour: 4000,
    price: 120000,
    icon: "bed-outline",
    color: "#16a085",
  },
  {
    id: 10,
    name: "Авиакомпания",
    type: "airline",
    incomePerHour: 7000,
    price: 200000,
    icon: "airplane-outline",
    color: "#3498db",
    dependent: true,
  },
];
